apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-vip-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-vip-role
subjects:
  - kind: ServiceAccount
    name: kube-vip
    namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-vip-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - configmaps
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip
  namespace: kube-system
